---

  - name: 2.1.1 Ensure chargen services are not enabled
    service: >
        name=chargen-dgram
        state=stopped
        enabled=no
    register: command_result
    failed_when: "command_result|failed and 'could not find' not in command_result.msg"
    tags:
      - section2
      - section2.1
      - section2.1.1

  - name: 2.1.1 Ensure chargen services are not enabled
    service: >
        name=chargen-stream
        state=stopped
        enabled=no
    register: command_result
    failed_when: "command_result|failed and 'could not find' not in command_result.msg"
    tags:
      - section2
      - section2.1
      - section2.1.1

  - name: 2.1.2 Ensure daytime services are not enabled
    service: >
        name=daytime-dgram
        state=stopped
        enabled=no
    register: command_result
    failed_when: "command_result|failed and 'could not find' not in command_result.msg"
    tags:
      - section2
      - section2.1
      - section2.1.2

  - name: 2.1.2 Ensure daytime services are not enabled
    service: >
        name=daytime-stream
        state=stopped
        enabled=no
    register: command_result
    failed_when: "command_result|failed and 'could not find' not in command_result.msg"
    tags:
      - section2
      - section2.1
      - section2.1.2

  - name: 2.1.3 Ensure discard services are not enabled
    service: >
        name=discard-dgram
        state=stopped
        enabled=no
    register: command_result
    failed_when: "command_result|failed and 'could not find' not in command_result.msg"
    tags:
      - section2  
      - section2.1  
      - section2.1.3

  - name: 2.1.3 Ensure discard services are not enabled 
    service: >
        name=discard-stream
        state=stopped
        enabled=no
    register: command_result
    failed_when: "command_result|failed and 'could not find' not in command_result.msg"
    tags:
      - section2
      - section2.1
      - section2.1.3

  - name: 2.1.4 Ensure echo services are not enabled
    service: >
        name=echo-dgram
        state=stopped
        enabled=no
    register: command_result
    failed_when: "command_result|failed and 'could not find' not in command_result.msg"
    tags:
      - section2  
      - section2.1  
      - section2.1.4

  - name: 2.1.4 Ensure echo services are not enabled
    service: >
        name=echo-stream
        state=stopped
        enabled=no
    register: command_result
    failed_when: "command_result|failed and 'could not find' not in command_result.msg"
    tags:
      - section2
      - section2.1
      - section2.1.4

  - name: 2.1.5 Ensure time services are not enabled
    service: >
        name=time-dgram
        state=stopped
        enabled=no
    register: command_result
    failed_when: "command_result|failed and 'could not find' not in command_result.msg"
    tags:
      - section2  
      - section2.1  
      - section2.1.5

  - name: 2.1.5 Ensure time services are not enabled
    service: >
        name=time-stream
        state=stopped
        enabled=no
    register: command_result
    failed_when: "command_result|failed and 'could not find' not in command_result.msg"
    tags:
      - section2
      - section2.1
      - section2.1.5

  - name: 2.1.6 Ensure tftp services are not enabled
    service: > 
        name=tftp
        state=stopped
        enabled=no
    register: command_result
    failed_when: "command_result|failed and 'could not find' not in command_result.msg"
    tags:
      - section2
      - section2.1
      - section2.1.6

  - name: 2.1.7 Ensure xinetd services are not enabled
    service: >
        name=xinetd
        state=stopped
        enabled=no
    register: command_result
    failed_when: "command_result|failed and 'could not find' not in command_result.msg"
    tags:
      - section2
      - section2.1
      - section2.1.7

  - name: 2.2.1.1 Ensure time synchronization is in use
    yum: >
      pkg=ntp
      state=installed    
    always_run: yes
    tags:
      - section2
      - section2.2
      - section2.2.1.1

  - name: 2.2.1.2 Ensure ntp is configured
    service: >
      name=ntpd
      state=started
      enabled=yes
    tags:
      - section2
      - section2.2
      - section2.2.1.2

  - name: 2.2.1.2 Ensure ntp is configured
    lineinfile: >
      dest=/etc/ntp.conf
      state=present
      regexp="^#?restrict default"
      line="restrict default kod nomodify notrap nopeer noquery"
    tags:
      - section2
      - section2.2
      - section2.2.1.2

  - name: 2.2.1.2 Ensure ntp is configured
    lineinfile: >
      dest=/etc/ntp.conf
      state=present
      regexp="^#?restrict -6 default"
      line="restrict -6 default kod nomodify notrap nopeer noquery"
      insertafter="^restrict default"
    tags:
      - section2
      - section2.2
      - section2.2.1.2

  - name: 2.2.2 Ensure X Window System is not installed 
    yum: >
      pkg=xorg-x11*
      state=absent
    tags:
      - section2
      - section2.2
      - section2.2.2

  - name: 2.2.3 Ensure Avahi Server is not enabled 
    service: >
        name=avahi-daemon
        state=stopped
        enabled=no
    register: command_result
    failed_when: "command_result|failed and 'could not find' not in command_result.msg"
    tags:
      - section2
      - section2.2
      - section2.2.3

  - name: 2.2.4 Ensure CUPS is not enabled   
    service: >  
        name=cups
        state=stopped
        enabled=no  
    register: command_result
    failed_when: "command_result|failed and 'could not find' not in command_result.msg"
    tags:
      - section2  
      - section2.2
      - section2.2.4

  - name: 2.2.5 Ensure DHCP server is not enabled        
    service: >
        name=dhcpd
        state=stopped
        enabled=no
    register: command_result
    failed_when: "command_result|failed and 'could not find' not in command_result.msg"
    tags:
      - section2
      - section2.2
      - section2.2.5

  - name: 2.2.6 Ensure LDAP server is not enabled        
    service: >
        name=slapd
        state=stopped
        enabled=no
    register: command_result
    failed_when: "command_result|failed and 'could not find' not in command_result.msg"
    tags:
      - section2
      - section2.2
      - section2.2.6

  - name: 2.2.7 Ensure NFS and RPC are not enabled     
    service: >
        name=nfs
        state=stopped
        enabled=no
    register: command_result
    failed_when: "command_result|failed and 'could not find' not in command_result.msg"
    tags:
      - section2
      - section2.2
      - section2.2.7

  - name: 2.2.7 Ensure NFS and RPC are not enabled
    service: >   
        name=rpcbind
        state=stopped
        enabled=no
    register: command_result
    failed_when: "command_result|failed and 'could not find' not in command_result.msg"
    tags:
      - section2
      - section2.2
      - section2.2.7
   
  - name: 2.2.8 Ensure DNS server is not enabled
    service: >   
        name=named
        state=stopped
        enabled=no
    register: command_result
    failed_when: "command_result|failed and 'could not find' not in command_result.msg"
    tags:
      - section2
      - section2.2
      - section2.2.8

  - name: 2.2.9 Ensure FTP Server is not enabled
    service: >
        name=vsftpd
        state=stopped
        enabled=no  
    register: command_result
    failed_when: "command_result|failed and 'could not find' not in command_result.msg"
    tags:
      - section2
      - section2.2
      - section2.2.9

  - name: 2.2.10 Ensure HTTP server is not enabled
    service: >
        name=httpd
        state=stopped
        enabled=no
    register: command_result
    failed_when: "command_result|failed and 'could not find' not in command_result.msg"
    tags:
      - section2
      - section2.2
      - section2.2.10

  - name: 2.2.11 Ensure IMAP and POP3 server is not enabled
    service: >
        name=dovecot
        state=stopped
        enabled=no  
    register: command_result
    failed_when: "command_result|failed and 'could not find' not in command_result.msg"
    tags:
      - section2
      - section2.2
      - section2.2.11

  - name: 2.2.12 Ensure Samba is not enabled
    service: >
        name=smb
        state=stopped
        enabled=no
    register: command_result
    failed_when: "command_result|failed and 'could not find' not in command_result.msg"
    tags:
      - section2
      - section2.2
      - section2.2.12

  - name: 2.2.13 Ensure HTTP proxy server is not enabled
    service: >
        name=squid
        state=stopped
        enabled=no
    register: command_result
    failed_when: "command_result|failed and 'could not find' not in command_result.msg"
    tags:
      - section2
      - section2.2
      - section2.2.13

  - name: 2.2.14 Ensure SNMP server is not enabled
    service: >
        name=snmpd
        state=stopped
        enabled=no
    register: command_result
    failed_when: "command_result|failed and 'could not find' not in command_result.msg"
    tags:
      - section2
      - section2.2
      - section2.2.14

  - name: 2.2.15 Ensure mail transfer agent is configured for local-only mode
    lineinfile: >
      dest=/etc/postfix/main.cf
      state=present
      regexp="^inet_interfaces"
      line="inet_interfaces = localhost"
    tags:
      - section2
      - section2.2
      - section2.2.15

  - name: 2.2.16 Ensure NIS server is not enabled
    service: >
        name=ypserv
        state=stopped
        enabled=no
    register: command_result
    failed_when: "command_result|failed and 'could not find' not in command_result.msg"
    tags:
      - section2
      - section2.2
      - section2.2.16

  - name: 2.2.17 Ensure rsh server is not enabled
    service: >
        name=rsh.socket
        state=stopped
        enabled=no
    register: command_result
    failed_when: "command_result|failed and 'could not find' not in command_result.msg"
    tags:
      - section2
      - section2.2
      - section2.2.17

  - name: 2.2.17 Ensure rsh server is not enabled
    service: >
        name=rlogin.socket
        state=stopped
        enabled=no   
    register: command_result
    failed_when: "command_result|failed and 'could not find' not in command_result.msg"
    tags:
      - section2
      - section2.2
      - section2.2.17

  - name: 2.2.17 Ensure rsh server is not enabled
    service: >
        name=rexec.socket
        state=stopped
        enabled=no   
    register: command_result
    failed_when: "command_result|failed and 'could not find' not in command_result.msg"
    tags:
      - section2
      - section2.2
      - section2.2.17

  - name: 2.2.18 Ensure telnet server is not enabled
    service: >
        name=telnet.socket
        state=stopped
        enabled=no   
    register: command_result
    failed_when: "command_result|failed and 'could not find' not in command_result.msg"
    tags:
      - section2
      - section2.2
      - section2.2.18

  - name: 2.2.19 Ensure tftp server is not enabled
    service: >
        name=tftp.socket
        state=stopped
        enabled=no   
    register: command_result
    failed_when: "command_result|failed and 'could not find' not in command_result.msg"
    tags:
      - section2
      - section2.2
      - section2.2.19

  - name: 2.2.20 Ensure rsync service is not enabled
    service: >
        name=rsyncd
        state=stopped
        enabled=no   
    register: command_result
    failed_when: "command_result|failed and 'could not find' not in command_result.msg"
    tags:
      - section2
      - section2.2
      - section2.2.20

  - name: 2.2.21 Ensure talk server is not enabled
    service: >
        name=ntalk
        state=stopped
        enabled=no   
    register: command_result
    failed_when: "command_result|failed and 'could not find' not in command_result.msg"
    tags:
      - section2
      - section2.2
      - section2.2.21

  - name: 2.3.1 Ensure NIS Client is not installed 
    yum: >
      pkg=ypbind
      state=absent
    tags:
      - section2
      - section2.3
      - section2.3.1

  - name: 2.3.2 Ensure rsh Client is not installed
    yum: >
      pkg=rsh
      state=absent 
    tags:
      - section2
      - section2.3
      - section2.3.2

  - name: 2.3.3 Ensure talk Client is not installed
    yum: >
      pkg=talk
      state=absent 
    tags:
      - section2
      - section2.3
      - section2.3.3

  - name: 2.3.4 Ensure telnet Client is not installed
    yum: >
      pkg=telnet
      state=absent 
    tags:
      - section2
      - section2.3
      - section2.3.4

  - name: 2.3.5 Ensure LDAP Client is not installed
    yum: >
      pkg=openldap-clients
      state=absent 
    tags:
      - section2
      - section2.3
      - section2.3.5
