---

  - name: 4.1.1.1 Ensure audit log storage size is configured
    lineinfile: >
      state=present
      dest=/etc/audit/auditd.conf
      regexp="^#?max_log_file ="
      line="max_log_file = {{ max_log_file }}"
    notify: Reload auditd Rules
    tags:
      - section4
      - section4.1
      - section4.1.1.1

  - name: 4.1.1.2 Ensure system is disabled when audit logs are full 
    lineinfile: >
      state=present
      dest=/etc/audit/auditd.conf
      regexp="^#?space_left_action ="
      line="space_left_action = {{ space_left_action }}"
    notify: Reload auditd Rules
    tags:
      - section4
      - section4.1
      - section4.1.1.2

  - name: 4.1.1.2 Ensure system is disabled when audit logs are full 
    lineinfile: >  
      state=present
      dest=/etc/audit/auditd.conf
      regexp="^#?action_mail_acct ="
      line="action_mail_acct = {{ action_mail_acct }}"
    notify: Reload auditd Rules
    tags:
      - section4  
      - section4.1
      - section4.1.1.2

  - name: 4.1.1.2 Ensure system is disabled when audit logs are full
    lineinfile: >
      state=present
      dest=/etc/audit/auditd.conf
      regexp="^#?admin_space_left_action ="
      line="admin_space_left_action = {{ admin_space_left_action }}"
    notify: Reload auditd Rules
    tags:
      - section4
      - section4.1
      - section4.1.1.2

  - name: 4.1.1.3 Ensure audit logs are not automatically deleted
    lineinfile: >
      state=present
      dest=/etc/audit/auditd.conf
      regexp="^#?max_log_file_action ="
      line="max_log_file_action = {{ max_log_file_action }}"
    notify: Reload auditd Rules
    tags:
      - section4  
      - section4.1
      - section4.1.1.3

  - name: 4.1.2 Ensure auditd service is enabled
    service: >
      name=auditd
      enabled=yes
      state=running
    tags:
      - section4
      - section4.1
      - section4.1.2

  - name: 4.1.3 Ensure auditing for processes that start prior to auditd is enabled
    lineinfile: >
      state=present
      dest=/etc/default/grub
      backrefs=yes
      regexp="(^GRUB_CMDLINE_LINUX=.*\"$)"
      line="\1 audit=1\""
    tags:
      - section4
      - section4.1
      - section4.1.3

  - name: 4.1.4 - 4.1.18 Configure audit rules
    copy: >
      src=files/audit.rules
      dest=/etc/audit/rules.d/audit.rules
    notify: Reload auditd Rules
    tags: 
      - section4
      - section4.1
      - section4.1.4
      - section4.1.5
      - section4.1.6
      - section4.1.7
      - section4.1.8
      - section4.1.9
      - section4.1.10
      - section4.1.11
      - section4.1.12
      - section4.1.13
      - section4.1.14
      - section4.1.15
      - section4.1.16
      - section4.1.17
      - section4.1.18

  - name: 4.2.1.1 Ensure rsyslog Service is enabled
    yum: >
      name=rsyslog
      state=present
    tags:
      - section4
      - section4.2
      - section4.2.1.1

  - name: 4.2.1.1 Ensure rsyslog Service is enabled
    service: >
      name=rsyslog
      enabled=yes
      state=started
    tags:
      - section4
      - section4.2
      - section4.2.1.1

  - name: 4.2.1.3 Ensure rsyslog default file permissions configured
    lineinfile: >  
      state=present 
      dest=/etc/rsyslog.conf
      regexp="^#?\$FileCreateMode"
      line="$FileCreateMode 0640"
    tags:
      - section4
      - section4.2
      - section4.2.1.3

  - name: 4.2.1.4 Ensure rsyslog is configured to send logs to a remote log host
    lineinfile: >
      state=present
      dest=/etc/rsyslog.conf
      regexp="^#?\*\.\*"
      line="*.* @@{{ rsyslog_dest }}"
    when: rsyslog_dest is defined
    tags:
      - section4
      - section4.2
      - section4.2.1.4

  - name: 4.2.1.5 Ensure remote rsyslog messages are only accepted on designated log hosts
    lineinfile: >
      state=present
      dest=/etc/rsyslog.conf
      line="$ModLoad imtcp.so"
    when: rsyslog_host
    tags:
      - section4
      - section4.2
      - section4.2.1.5

  - name: 4.2.1.5 Ensure remote rsyslog messages are only accepted on designated log hosts
    lineinfile: >
      state=present
      dest=/etc/rsyslog.conf
      line="$InputTCPServerRun 514"
    when: rsyslog_host
    tags:
      - section4
      - section4.2
      - section4.2.1.5

  - name: 4.2.4 Ensure permissions on all logfiles are configured
    shell: find /var/log -type f -exec chmod g-wx,o-rwx {} +
    tags:
      - section4
      - section4.2
      - section4.2.4

  - name: 4.3 Ensure logrotate is configured
    lineinfile: >
      state=present
      dest=/etc/logrotate.conf
      regexp="^#?compress"
      line="compress"
    tags:
      - section4
      - section4.3
