---

  - name: 5.1.1 Ensure cron daemon is enabled
    service: >
      name=crond
      enabled=yes
      state=started
    tags:
      - section5
      - section5.1
      - section5.1.1

  - name: 5.1.2 - 5.1.7 Ensure permissions on cron files are configured 
    file: >
      path={{ item }}
      owner=root
      group=root
      mode=0600
    with_items:
      - /etc/crontab
      - /etc/cron.hourly
      - /etc/cron.daily
      - /etc/cron.weekly
      - /etc/cron.monthly
      - /etc/cron.d
    tags:
      - section5
      - section5.1
      - section5.1.2
      - section5.1.3
      - section5.1.4
      - section5.1.5
      - section5.1.6
      - section5.1.7

  - name: 5.1.8 Ensure at/cron is restricted to authorized users
    file: >
      path=/etc/at.deny
      state=absent
    tags:
      - section5
      - section5.1
      - section5.1.8

  - name: 5.1.8 Ensure at/cron is restricted to authorized users
    file: >
      path=/etc/cron.deny
      state=absent
    tags:
      - section5
      - section5.1
      - section5.1.8

  - name: 5.1.8 Ensure at/cron is restricted to authorized users
    file: >
      path=/etc/at.allow
      state=touch
      owner=root
      group=root
      mode=0600
    tags:
      - section5
      - section5.1
      - section5.1.8

  - name: 5.1.8 Ensure at/cron is restricted to authorized users
    file: >
      path=/etc/cron.allow
      state=touch
      owner=root
      group=root
      mode=0600
    tags:
      - section5
      - section5.1
      - section5.1.8

  - name: 5.2.1 Ensure permissions on /etc/ssh/sshd_config are configured
    file: >
      path=/etc/ssh/sshd_config
      owner=root
      group=root
      mode=0600
    tags:
      - section5
      - section5.2
      - section5.2.1

  - name: 5.2.2 Ensure SSH Protocol is set to 2
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^#?Protocol " 
      line="Protocol 2"
    notify: Reload sshd
    tags:
      - section5
      - section5.2
      - section5.2.2

  - name: 5.2.3 Ensure SSH LogLevel is set to INFO
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^#?LogLevel "
      line="LogLevel INFO"
    notify: Reload sshd
    tags:
      - section5
      - section5.2
      - section5.2.3

  - name: 5.2.4 Ensure SSH X11 forwarding is disabled
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^#?X11Forwarding "
      line="X11Forwarding no"
    notify: Reload sshd
    tags:
      - section5
      - section5.2
      - section5.2.4

  - name: 5.2.5 Ensure SSH MaxAuthTries is set to 4 or less
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^#?MaxAuthTries "
      line="MaxAuthTries 4"
    notify: Reload sshd
    tags:
      - section5
      - section5.2
      - section5.2.5

  - name: 5.2.6 Ensure SSH IgnoreRhosts is enabled 
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^#?IgnoreRhosts "
      line="IgnoreRhosts yes"
    notify: Reload sshd
    tags:
      - section5
      - section5.2
      - section5.2.6

  - name: 5.2.7 Ensure SSH HostbasedAuthentication is disabled
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^#?HostbasedAuthentication "
      line="HostbasedAuthentication no"
    notify: Reload sshd
    tags:
      - section5
      - section5.2
      - section5.2.7

  - name: 5.2.8 Ensure SSH root login is disabled 
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^#?PermitRootLogin "
      line="PermitRootLogin no"
    notify: Reload sshd
    tags:
      - section5
      - section5.2
      - section5.2.8

  - name: 5.2.9 Ensure SSH PermitEmptyPasswords is disabled 
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^#?PermitEmptyPasswords "
      line="PermitEmptyPasswords no"
    notify: Reload sshd
    tags:
      - section5
      - section5.2
      - section5.2.9

  - name: 5.2.10 Ensure SSH PermitUserEnvironment is disabled
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^#?PermitUserEnvironment "
      line="PermitUserEnvironment no"
    notify: Reload sshd
    tags:
      - section5
      - section5.2
      - section5.2.10

  - name: 5.2.11 Ensure only approved ciphers are used
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^#?Ciphers "
      line="Ciphers aes256-ctr,aes192-ctr,aes128-ctr"
    notify: Reload sshd
    tags:
      - section5
      - section5.2
      - section5.2.11

# - name: 5.2.12 Ensure only approved MAC algorithms are used
 
  - name: 5.2.13 Ensure SSH Idle Timeout Interval is configured
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^#?ClientAliveInterval "
      line="ClientAliveInterval 300"
    notify: Reload sshd
    tags:
      - section5
      - section5.2
      - section5.2.13

  - name: 5.2.13 Ensure SSH Idle Timeout Interval is configured
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^#?ClientAliveCountMax "
      line="ClientAliveCountMax 0"
    notify: Reload sshd
    tags:
      - section5
      - section5.2
      - section5.2.13

  - name: 5.2.14 Ensure SSH LoginGraceTime is set to one minute or less
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^#?LoginGraceTime "
      line="LoginGraceTime 60"
    notify: Reload sshd
    tags:  
      - section5
      - section5.2
      - section5.2.14

  - name: 5.2.15 Ensure SSH access is limited
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^#?AllowGroups "
      line="AllowGroups {{ ssh_allow_groups }}"
    when: ssh_allow_groups is defined
    notify: Reload sshd
    tags:
      - section5
      - section5.2
      - section5.2.15

  - name: 5.2.15 Ensure SSH access is limited
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^#?AllowUsers "
      line="AllowUsers {{ ssh_allow_users }}"
    when: ssh_allow_users is defined
    notify: Reload sshd
    tags:
      - section5
      - section5.2
      - section5.2.15

  - name: 5.2.15 Ensure SSH access is limited
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^#?DenyGroups "
      line="DenyGroups {{ ssh_deny_groups }}"
    when: ssh_deny_groups is defined
    notify: Reload sshd
    tags:
      - section5
      - section5.2
      - section5.2.15

  - name: 5.2.15 Ensure SSH access is limited
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^#?DenyUsers "
      line="DenyUsers {{ ssh_deny_users }}"
    when: ssh_deny_users is defined
    notify: Reload sshd
    tags:
      - section5
      - section5.2
      - section5.2.15

  - name: 5.2.16 Ensure SSH warning banner is configured 
    lineinfile: >
      dest=/etc/ssh/sshd_config
      regexp="^#?Banner "
      line="Banner /etc/issue.net"
    notify: Reload sshd
    tags:
      - section5
      - section5.2
      - section5.2.16

  - name: 5.3.1 Ensure password creation requirements are configured
    lineinfile: >
      dest=/etc/security/pwquality.conf
      regexp="^#?minlen=.*"
      line="minlen=14"
    tags:
      - section5
      - section5.3
      - section5.3.1

  - name: 5.3.1 Ensure password creation requirements are configured
    lineinfile: >
      dest=/etc/security/pwquality.conf
      regexp="^#?dcredit=.*"
      line="dcredit=-1"
    tags:
      - section5
      - section5.3
      - section5.3.1

  - name: 5.3.1 Ensure password creation requirements are configured
    lineinfile: >
      dest=/etc/security/pwquality.conf
      regexp="^#?ucredit=.*"
      line="ucredit=-1"
    tags:
      - section5
      - section5.3
      - section5.3.1

  - name: 5.3.1 Ensure password creation requirements are configured
    lineinfile: >
      dest=/etc/security/pwquality.conf
      regexp="^#?ocredit=.*"
      line="ocredit=-1"
    tags:
      - section5
      - section5.3
      - section5.3.1

  - name: 5.3.1 Ensure password creation requirements are configured
    lineinfile: >
      dest=/etc/security/pwquality.conf
      regexp="^#?lcredit=.*"
      line="lcredit=-1"
    tags:
      - section5
      - section5.3
      - section5.3.1

  - name: 5.3.3 Ensure password reuse is limited
    lineinfile: >
      dest=/etc/pam.d/system-auth
      backrefs=yes
      regexp="(^password\s+sufficient\s+pam_unix.so.*)$(?!remember=5)"
      line="\1 remember=5"
    tags:
      - section5
      - section5.3
      - section5.3.3

  - name: 5.3.4 Ensure password hashing algorithm is SHA-512
    lineinfile: >
      dest=/etc/pam.d/system-auth
      backrefs=yes
      regexp="(^password\s+sufficient\s+pam_unix.so.*)$(?!sha512)"
      line="\1 sha512"
    tags:
      - section5
      - section5.3
      - section5.3.4

  - name: 5.4.1.1 Ensure password expiration is 90 days or less 
    lineinfile: >
      dest=/etc/login.defs
      regexp="^#?PASS_MAX_DAYS "
      line="PASS_MAX_DAYS 90"
    tags:
      - section5
      - section5.4
      - section5.4.1.1

  - name: 5.4.1.2 Ensure minimum days between password changes is 7 or more
    lineinfile: >
      dest=/etc/login.defs
      regexp="^#?PASS_MIN_DAYS "
      line="PASS_MIN_DAYS 7"
    tags:
      - section5  
      - section5.4
      - section5.4.1.2

  - name: 5.4.1.3 Ensure password expiration warning days is 7 or more
    lineinfile: >
      dest=/etc/login.defs
      regexp="^#?PASS_WARN_DAYS "
      line="PASS_WARN_DAYS 7"
    tags:
      - section5
      - section5.4  
      - section5.4.1.3

  - name: 5.4.2 Ensure system accounts are non-login
    shell: egrep -v "^\+" /etc/passwd | awk -F':' '($1!="root" && $1!="sync" && $1!="shutdown" && $1!="halt" && $3<1000 && $7!="/sbin/nologin" && $7!="/bin/false") {print $1}'
    register: enabled_system_accounts
    changed_when: false
    tags:
      - section5
      - section5.4
      - section5.4.2

  - name: 5.4.2 Ensure system accounts are non-login
    command: /usr/sbin/usermod -s /sbin/nologin {{ item }}
    with_items: '{{ enabled_system_accounts.stdout_lines }}'
    tags:
      - section5
      - section5.4
      - section5.4.2

  - name: 5.4.3 Ensure default group for the root account is GID 0
    user: >
      name=root
      group=root
    tags:
      - section5
      - section5.4
      - section5.4.3

  - name: 5.4.4 Ensure default user umask is 027 or more restrictive
    lineinfile: 
      state=present
      create=yes
      dest=/etc/profile.d/cis.sh
      line="umask 077"
    ignore_errors: true
    tags:
      - section5
      - section5.4
      - section5.4.4
  
  - name: Ensure that /etc/profile.d/cis.sh has correct owner, group and mode
    file: 
      path=/etc/profile.d/cis.sh 
      owner=root
      group=root
      mode=0644
    changed_when: false
    tags:
      - section5
      - section5.4
      - section5.4.4

  - name: 5.6 Ensure access to the su command is restricted
    lineinfile: >
      dest=/etc/pam.d/su
      backrefs=yes
      regexp="(^#?auth\s+required\s+pam_wheel.so use_uid)"
      line="auth\trequired\tpam_wheel.so use_uid"
    tags: 
      - section5
      - section5.6
