---

  - name: Reload auditd Rules
    command: /usr/bin/pkill -HUP -P 1 auditd

  - name: Reload prelinking
    command: /usr/sbin/prelink -ua

  - name: Reload sshd
    shell: systemctl reload sshd
    register: result
    changed_when: "result.rc == 0"
    failed_when: "result.rc not in [0, 7]"
